[build]
  command = "npm run build"
  publish = "client/build"

[dev]
  command = "npm start"
  targetPort = 3000       # react-scripts start default
  port = 8888             # Netlify’s dev server port
  autoLaunch = true