[build]
  functions = "client/netlify/functions"
  command = "npm run build"
  publish = "client/build"

[dev]
  command = "npm start"
  functions = "client/netlify/functions"
  targetPort = 3000       # react-scripts start default
  port = 8888             # Netlify’s dev server port
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/client/netlify/functions/server/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"