[build]
  base = "client"
  functions = ".netlify/functions"
  command = "npm run build"
  publish = "client/build"

[dev]
  command = "npm start"
  functions = ".netlify/functions"
  targetPort = 3000       # react-scripts start default
  port = 8888             # Netlify’s dev server port
  autoLaunch = false

  [[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200